### ISSUE TITLE
this.context.pageContext.web.absoluteUrl not taking current web URL

### ISSUE THREAD

**Issue by KaushalKhamar** [SharePoint/sp-dev-fx-property-controls#171]
#### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question

#### Version
1.14
#### Expected / Desired Behavior / Question
I am using list picker control. I need to get lists from sub site in modern page. And when i put web part in page i am getting error and when i troubleshoot this issue i have found that current web url is wrong.

**this.context.pageContext.web.absoluteUrl** not taking current web URL. 

Instead of this it is taking url (_https://kaushalkhamar.sharepoint.com/sites/mysite_) of App web url i.e. (_"https://kaushalkhamar-app0c7ded7ed12d49eab97d77a8fcbc5820.sharepoint.com/sites/mysite"_)

**Comment by AJIXuMuK** [comment]
Hi @KaushalKhamar,
First of all, `this.context` is a web part’s property. It is not related to the Property Pane Controls. 
So, you need to post your question in (sp-dev-docs)[https://github.com/SharePoint/sp-dev-docs/issues] repo instead of this one. 
Second, when you post it there, please, provide more details. Screenshot of the page and page url would be great, as well as description of how you want to use a SPFx web part.

**Comment by KaushalKhamar** [comment]
Hello @AJIXuMuK ,

I got to know that i have used isolated domain functionality in this webpart that is why it has its own context. Due to which issue is occurring. Now issue has been resolved. You can close this issue.

Thanks for help.
