### ISSUE TITLE
PropertyFieldPeoplePicker validation error does not clear as expected.

### ISSUE THREAD

**Issue by SamipPatel** [SharePoint/sp-dev-fx-property-controls#68]
#### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question

#### Version

[1.6.0]

#### Expected / Desired Behavior / Question
Added validation function to onGetErrorMessage property of a PropertyFieldPeoplePicker field.  Failed validation on purpose to display error message.  Then updated to a valid value and expected the error message to clear. 

#### Observed Behavior
Error message is still displayed after a valid value is selected.

**Comment by estruyf** [comment]
Thanks for reporting this.

**Comment by estruyf** [comment]
@SamipPatel this issue just got fixed in the latest beta.

![people-issue-fixed](https://user-images.githubusercontent.com/2900833/41229028-c27c6098-6d7a-11e8-9190-f2b1c799fb16.gif)

If you want to test it out, here are some instruction of testing out the latest beta version: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/

**Comment by estruyf** [comment]
This just got released so going to close this issue. Feel free to open it again it's not fixed.
